sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root1234
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tExotnWt8co92QoN19W
    accessKeySecret: ZFLH9eWWZMOxmLPlQCf8BxACbqTZbm
    bucketName: web-tliass12